<a href="https://colab.research.google.com/github/acpotgieter/geog510/blob/Lab-4/lab_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 4

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/giswqs/geog-510/blob/main/book/labs/lab_04.ipynb)

## Exercise 1: Variable Assignment and Basic Operations

Create variables to store the following geospatial data:

- The latitude and longitude of New York City: 40.7128, -74.0060.
- The population of New York City: 8,336,817.
- The area of New York City in square kilometers: 783.8.

Perform the following tasks:

1. Calculate and print the population density of New York City (population per square kilometer).
2. Print the coordinates in the format "Latitude: [latitude], Longitude: [longitude]".

In [ ]:
#Variables
latitude_nyc = 40.7128
longitude_nyc = -74.0060
population_nyc = 8253000
area_nyc_mi2 = 302.6

#Calculation of Population Density
population_density_nyc = population_nyc / area_nyc_mi2
print(f"Population Density of NYC: {population_density_nyc:.2f} people/mi^2")

print(f"Latitude: {latitude_nyc}, Longitude: {longitude_nyc}")




Population Density of NYC: 27273.63 people/mi^2
Latitude: 40.7128, Longitude: -74.006


## Exercise 2: Working with Strings

Create a string variable to store the name of a city, such as "San Francisco". Perform the following operations:

1. Convert the string to lowercase and print the result.
2. Convert the string to uppercase and print the result.
3. Replace "San" with "Los" in the city name and print the new string.

In [ ]:
#Variable
city_name = "San Francisco"

#Lowercase Converstion
city_name_lower = city_name.lower()
print(city_name_lower)

#Uppercase Coverstion
city_name_upper = city_name.upper()
print(city_name_upper)

#Name Replacement
city_name_replaced = city_name.replace("San", "Los")
print(city_name_replaced)

san francisco
SAN FRANCISCO
Los Francisco


## Exercise 3: Using Lists

Create a list of tuples, where each tuple contains the name of a city and its corresponding latitude and longitude:

- New York City: (40.7128, -74.0060)
- Los Angeles: (34.0522, -118.2437)
- Chicago: (41.8781, -87.6298)

Perform the following tasks:

1. Add a new city (e.g., Miami: (25.7617, -80.1918)) to the list.
2. Print the entire list of cities.
3. Slice the list to print only the first two cities.

In [ ]:
#List
cities = [
    ("New York City", 40.7128, -70.0060),
    ("Los Angeles", 34.0522, -118.2437),
    ("Chicago", 41.8781, -87.6298),
]

#Add City
cities.append(("Miami", 25.7617, -80.1918))
print("All Cities:", cities)

#Slice
print("First Two Cities", cities[:2])

All Cities: [('New York City', 40.7128, -70.006), ('Los Angeles', 34.0522, -118.2437), ('Chicago', 41.8781, -87.6298), ('Miami', 25.7617, -80.1918)]
First Two Cities [('New York City', 40.7128, -70.006), ('Los Angeles', 34.0522, -118.2437)]


## Exercise 4: Using Tuples

Create a tuple to store the coordinates (latitude, longitude) of the Eiffel Tower: (48.8584, 2.2945). Perform the following tasks:

1. Access and print the latitude and longitude values from the tuple.
2. Try to change the latitude value to 48.8585. What happens? Explain why.

In [ ]:
#Tupel
eiffel_tower_coords = (48.8584, 2.2945)

#Access from tuepel
latitude_eiffel = eiffel_tower_coords[:0]
longitude_eiffel = eiffel_tower_coords[:1]
print(f"Latitude: {latitude_eiffel}, Longitude: {longitude_eiffel}")

#Tuples cannot be modified, attempting to will result in an error

Latitude: (), Longitude: (48.8584,)


## Exercise 5: Working with Sets

Create a set of countries you have visited, such as {"USA", "France", "Germany"}. Perform the following tasks:

1. Add a new country to the set.
2. Try to add the same country again. What happens?
3. Print the updated set.

In [ ]:
#Set
visited_countries = {"USA", "France", "Germany"}

#Addded country
visited_countries.add("South Africa")

#Try addeding again
visited_countries.add("South Africa")
#No error and name is still only printed once.

print("Visited Countries:", visited_countries)

Visited Countries: {'France', 'South Africa', 'Germany', 'USA'}


## Exercise 6: Working with Dictionaries

Create a dictionary to store information about a specific geospatial feature, such as a river:

- Name: "Amazon River"
- Length: 6400 km
- Countries: ["Brazil", "Peru", "Colombia"]

Perform the following tasks:

1. Add a new key-value pair to the dictionary to store the river's average discharge (e.g., 209,000 m³/s).
2. Update the length of the river to 6992 km.
3. Print the dictionary.

In [ ]:
#Dictionary
amazon_river = {
    "Name": "Amazon River",
    "Length": 6400, #in km
    "Countries": ["Brazil", "Peru", "Colombia"],
}

#Add key-value
amazon_river["Discharge"] = 209000 #in m3/s

#Update length
amazon_river["Length"] = 6992 #in km

print(amazon_river)

{'Name': 'Amazon River', 'Length': 6992, 'Countries': ['Brazil', 'Peru', 'Colombia'], 'Discharge': 209000}


## Exercise 7: Nested Data Structures

Create a dictionary to represent a city that contains the city's name, population, and coordinates (latitude, longitude):

- Name: "Tokyo"
- Population: 13,515,271
- Coordinates: (35.6895, 139.6917)

Perform the following tasks:

1. Access and print the population of the city.
2. Access and print the city's latitude.
3. Update the population to 14,000,000 and print the updated dictionary.

In [ ]:
#Dictionary
tokyo = {"Name": "Tokyo", "Population": 13151271, "Coordinates": (35.6895, 139.6917)}

#Population Print
print("Population of Tokyo:", tokyo["Population"])

#Coordiantes Print
print("Tokyo Latitude:", tokyo["Coordinates"][0])

#Population update
tokyo["Population"] = 14000000

print("City of Tokyo Information:", tokyo)


Population of Tokyo: 13151271
Tokyo Latitude: 35.6895
City of Tokyo Information: {'Name': 'Tokyo', 'Population': 14000000, 'Coordinates': (35.6895, 139.6917)}


## Exercise 8: List Operations

Given the list of cities from Exercise 3, perform the following operations:

1. Sort the list of cities alphabetically by name.
2. Create a new list that contains only the city names.
3. Remove the last city from the original list and print the updated list.

In [ ]:
#City List
cities = [
    ("New York City", 40.7128, -74.0060),
    ("Los Angeles", 34.0522, -118.2437),
    ("Chicago", 41.8781, -87.6298),
    ("Miami", 25.7617, -80.1918),
]

#Sort cities alphabetically
cities_sorted = sorted(cities, key=lambda city:city[0])
print("Cities in Alphabetical Order:", cities_sorted)

#Only city names
city_name = [city[0] for city in cities]
print("City Names:", city_name)

#Remove last city
cities.pop()
print("Updates Cities:", cities)


Cities in Alphabetical Order: [('Chicago', 41.8781, -87.6298), ('Los Angeles', 34.0522, -118.2437), ('Miami', 25.7617, -80.1918), ('New York City', 40.7128, -74.006)]
City Names: ['New York City', 'Los Angeles', 'Chicago', 'Miami']
Updates Cities: [('New York City', 40.7128, -74.006), ('Los Angeles', 34.0522, -118.2437), ('Chicago', 41.8781, -87.6298)]


## Exercise 9: Dictionary Operations

Using the dictionary from Exercise 6, perform the following tasks:

1. Check if the key "Length" exists in the dictionary.
2. Print all the keys in the dictionary.
3. Print all the values in the dictionary.

In [ ]:
amazon_river = {
    "Name": "Amazon River",
    "Length": 6992,
    "Countries": ["Brazil", "Peru", "Colombia"],
    "Discharge": 209000,
}

#Check Length Key
if "Length" in amazon_river:
    print("Key 'Length' Exists in Dictrionary")

#Print all keys
print("Keys in Dictionary:", amazon_river.keys())

#Print all values
print("Values in Dictionary:", amazon_river.values())

Key 'Length' Exists in Dictrionary
Keys in Dictionary: dict_keys(['Name', 'Length', 'Countries', 'Discharge'])
Values in Dictionary: dict_values(['Amazon River', 6992, ['Brazil', 'Peru', 'Colombia'], 209000])


## Exercise 10: Practical Application

Imagine you have a list of tuples, each representing a location with its name, latitude, and longitude:

In [ ]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]

Perform the following tasks:

1. Create a new list that contains only the names of the locations.
2. Create a dictionary where the keys are location names and the values are tuples of their coordinates.
3. Print the latitude of "K2" using the dictionary.

In [ ]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]

#Location names list
location_names = [location[0] for location in locations]
print("Location Names:", location_names)

#Dictionary
location_dict = {location[0]: (location[1],location[2]) for location in locations}
print("Location Dictionary:", location_dict)

#Latitude Print
print("K2 Latitude:", location_dict["K2"][0])

Location Names: ['Mount Everest', 'K2', 'Kangchenjunga']
Location Dictionary: {'Mount Everest': (27.9881, 86.925), 'K2': (35.8808, 76.5155), 'Kangchenjunga': (27.7025, 88.1475)}
K2 Latitude: 35.8808


## Exercise 11: Manipulating Geographic Location Strings

- Create a string that represents the name of a geographic feature (e.g., `"Amazon River"`).
- Convert the string to lowercase and then to uppercase.
- Concatenate the string with the name of the country (e.g., `"Brazil"`) to create a full location name.
- Repeat the string three times, separating each repetition with a dash (`-`).

In [ ]:
#String
geo_feature = "Amazon River"

#String Coverts
geo_feature_lower = geo_feature.lower()
print(geo_feature_lower)
geo_feature_upper = geo_feature.upper()
print(geo_feature_upper)

#Concatenate
full_feature = geo_feature + ", Brazil"
print(full_feature)

#Repeated Dashes
repeated_feature = (geo_feature + "-") *2 + geo_feature
print(repeated_feature)

amazon river
AMAZON RIVER
Amazon River, Brazil
Amazon River-Amazon River-Amazon River


## Exercise 12: Extracting and Formatting Coordinates

- Given a string with the format `"latitude, longitude"` (e.g., `"40.7128N, 74.0060W"`), extract the numeric values of latitude and longitude.
- Convert these values to floats and remove the directional indicators (`N`, `S`, `E`, `W`).
- Format the coordinates into a `POINT` WKT string (e.g., `"POINT(-74.0060 40.7128)"`).

In [ ]:
#String
coordinates = "40.7128N, 74.0060W"

#Extraction
lat, lon = coordinates.split(", ")

latitude = float(lat[:-1])
longitude = float(lon[:-1])
print('Coordinates:', latitude, ",", longitude)

wtk_point = f"POINT({longitude} {latitude})"
print(wtk_point)


Coordinates: 40.7128 , 74.006
POINT(74.006 40.7128)


## Exercise 13: Building Dynamic SQL Queries

- Given a table name and a condition, dynamically build an SQL query string.
- Example: If `table_name = "cities"` and `condition = "population > 1000000"`, the query should be `"SELECT * FROM cities WHERE population > 1000000;"`.
- Add additional conditions dynamically, like `AND` clauses.

In [ ]:
table_name = "provinces"
condition = "population > 1000000"

#Query
sql_query = f"SELECT * FROM {table_name} WHERE {condition};"
print(sql_query)

#Additional conditions
condition_secondary = "country = South Africa"
sql_query_country = (
    f"SELCT * FROM {table_name} WHERE {condition} AND {condition_secondary};"
)
print(sql_query_country)


SELECT * FROM provinces WHERE population > 1000000;
SELCT * FROM provinces WHERE population > 1000000 AND country = South Africa;


## Exercise 14: String Normalization and Cleaning

- Given a list of city names with inconsistent formatting (e.g., `[" new york ", "Los ANGELES", "   CHICAGO"]`), normalize the names by:
  - Stripping any leading or trailing whitespace.
  - Converting them to title case (e.g., `"New York"`, `"Los Angeles"`, `"Chicago"`).
- Ensure that the output is a clean list of city names.

In [ ]:
cities = [" new york ", "Los ANGELES", " CHICAGO"]

#Cleaning
cleaned_cities = [city.strip().title() for city in cities]
print(cleaned_cities)

['New York', 'Los Angeles', 'Chicago']


## Exercise 15: Parsing and Extracting Address Information

- Given a string in the format `"Street, City, Country"` (e.g., `"123 Main St, Springfield, USA"`), write a function that parses the string into a dictionary with keys `street`, `city`, and `country`.
- The function should return a dictionary like `{"street": "123 Main St", "city": "Springfield", "country": "USA"}`.

In [ ]:
#Function
def parsed_address(address):
    street, city, country = address.split(", ")
    return {"street": street, "city": city, "country": country}

address = "123 Main St, Springfield, USA"
parsed_address = parsed_address(address)
print(parsed_address)


{'street': '123 Main St', 'city': 'Springfield', 'country': 'USA'}


## Exercise 16: Using For Loops to Process Coordinate Lists

- Create a list of tuples representing coordinates (latitude, longitude).
- Write a `for` loop that prints each coordinate and indicates whether it is in the Northern or Southern Hemisphere based on the latitude.

In [ ]:
#Coordinates
coordinates = [(38.1234, -110.6486), (45.3657, -5.9362), (-15.8365, 112.8234), (-8.7364, 105.8365)]

#Loop function
for lat, lon in coordinates:
    hemisphere = "Northern" if lat > 0 else "Southern"
    print(f"Coordinate ({lat}, {lon}) is in the {hemisphere} Hemisphere.")

Coordinate (38.1234, -110.6486) is in the Northern Hemisphere.
Coordinate (45.3657, -5.9362) is in the Northern Hemisphere.
Coordinate (-15.8365, 112.8234) is in the Southern Hemisphere.
Coordinate (-8.7364, 105.8365) is in the Southern Hemisphere.


## Exercise 17: While Loops for Iterative Processing

- Create a list of coordinates (latitude, longitude).
- Write a `while` loop that continues to print each coordinate until it encounters a coordinate with a negative latitude.
- Stop the loop once this condition is met.

In [ ]:
#Coordinates
coordinates = [(38.1234, -110.6486), (45.3657, -5.9362), (-15.8365, 112.8234), (-8.7364, 105.8365)]
index = 0

#While loop function
while index < len(coordinates):
    lat, lon = coordinates[index]
    if lat < 0:
        print(f"Encountered negative latitude at ({lat}, {lon}). Stopping.")
        break
    print(f"Processing coordinate: ({lat}, {lon})")
    index +=1


Processing coordinate: (38.1234, -110.6486)
Processing coordinate: (45.3657, -5.9362)
Encountered negative latitude at (-15.8365, 112.8234). Stopping.


## Exercise 18: Conditional Logic in Loops

- Create a list of coordinates and use a `for` loop to iterate over them.
- Use an `if-elif-else` statement inside the loop to classify each coordinate based on its longitude:
  - Print `"Eastern Hemisphere"` if the longitude is greater than 0.
  - Print `"Western Hemisphere"` if the longitude is less than 0.

In [ ]:
#Coordinates
coordinates = [(38.1234, -110.6486), (45.3657, -5.9362), (-15.8365, 112.8234), (-8.7364, 105.8365)]

#Loop function
for lat, lon in coordinates:
    if lon > 0:
        print(f"Coordinate ({lat}, {lon}) is in the Eastern Hemisphere.")
    elif lon < 0:
        print(f"Coordinate ({lat}, {lon}) is in the Western Hemisphere.")
    else:
        print(f"Coordinate ({lat}, {lon}) is on the Prime Meridian.")

Coordinate (38.1234, -110.6486) is in the Western Hemisphere.
Coordinate (45.3657, -5.9362) is in the Western Hemisphere.
Coordinate (-15.8365, 112.8234) is in the Eastern Hemisphere.
Coordinate (-8.7364, 105.8365) is in the Eastern Hemisphere.


## Exercise 19: Filtering Data with Combined Loops and Conditionals

- Given a list of coordinates, filter out and store only those located in the Southern Hemisphere (latitude < 0).
- Count the number of coordinates that meet this condition and print the result.

In [ ]:
#List
coordinates = [
    (38.1234, -110.6486),
    (45.3657, -5.9362),
    (-15.8365, 112.8234),
    (-8.7364, 105.8365)
]

#Southern Coordinates filter
southern_hemisphere = []

for lat, lon in coordinates:
    if lat < 0:
        southern_hemisphere.append((lat, lon))

print(f"Coordinates in the Southern Hemisphere: {southern_hemisphere}")
print(f"Number of Coordinates in the Southern Hemisphere: {len(southern_hemisphere)}")

Coordinates in the Southern Hemisphere: [(-15.8365, 112.8234), (-8.7364, 105.8365)]
Number of Coordinates in the Southern Hemisphere: 2


## Exercise 20: Generating and Analyzing Random Coordinates

- Write a program that generates random coordinates (latitude between [-90, 90] degrees and longitude between [-180, 180] degrees).
- Use a `while` loop to keep generating coordinates until a pair with both latitude and longitude greater than 50 is generated.
- Print each generated coordinate and the final coordinate that meets the condition.

In [ ]:
#Get random
import random

#Get random coordinates
def random_coordinate():
    latitude = random.uniform(-90, 90)
    longitude = random.uniform(-180, 180)
    return latitude, longitude

#While loop
while True:
    lat, lon = random_coordinate()
    print(f"Randomly Generated Coordinate: ({lat:.4f}, {lon:.4f})")
    if lat > 50 and lon > 50:
        print(f"Final Coordinate with Latitude and Longitude Greater Than 50: ({lat:.4f}, {lon:.4f})")
        break


Randomly Generated Coordinate: (21.4616, 38.1191)
Randomly Generated Coordinate: (-79.2980, -50.0499)
Randomly Generated Coordinate: (-56.3144, 83.5999)
Randomly Generated Coordinate: (17.5610, -25.6250)
Randomly Generated Coordinate: (-75.4544, 53.7757)
Randomly Generated Coordinate: (-7.9545, -67.9205)
Randomly Generated Coordinate: (-58.4131, -138.9306)
Randomly Generated Coordinate: (0.0944, 93.8917)
Randomly Generated Coordinate: (70.2557, 105.7267)
Final Coordinate with Latitude and Longitude Greater Than 50: (70.2557, 105.7267)


## Submission Requirements

Complete the exercises above and and upload the notebook to your GitHub repository. Make sure the notebook has a Colab badge at the top so that it can be easily opened in Google Colab. Submit the URL of the notebook to Canvas.